FROM hypriot/rpi-node:latest

MAINTAINER Björn Kjeholt <dev@kjeholt.se>

RUN apt-get update && \
    apt-get install -y vim && \
    apt-get clean 

RUN mkdir -p /usr/src/app && \
    mkdir -p /usr/src/app/js && \
    mkdir -p /usr/src/app/script && \
    npm install serialport --build-from-source=serialport
    
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/package-original.json
RUN \
    sed 's/TestWrapper/js\/main/g' package-original.json > package.json && \
    rm -rf node_modules nbproject && \
    echo "----------------"

RUN npm install

# Bundle app source
COPY js /usr/src/app/js
COPY Scripts /usr/src/app/script
COPY testport_cz.js /usr/src/app/testport_cz.js

CMD [ "npm", "start" ]

